from main.models.child import Child
from main.models.tutor import Tutor
from main.models.room import Room
from main.models.article import Article
from main.models.disease import Disease
from main.models.economy import Economy
from main.models.expedient import Expedient
from main.models.family_pickup import FamilyPickup
from main.models.intolerance import Intolerance
from main.models.attendance import Attendance
