# Generated by Django 4.1.7 on 2023-02-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_article', models.TextField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_child', models.CharField(max_length=32)),
                ('ci_child', models.CharField(max_length=11, unique=True)),
                ('year', models.IntegerField()),
                ('care_area', models.CharField(max_length=32)),
                ('eyes_color', models.CharField(max_length=32)),
                ('hair_color', models.CharField(max_length=32)),
                ('skin_color', models.CharField(max_length=32)),
                ('cp', models.CharField(max_length=32)),
                ('address_child', models.CharField(max_length=128)),
                ('age', models.IntegerField(max_length=3)),
                ('weight', models.IntegerField(max_length=3)),
                ('sexo', models.CharField(choices=[('female', 'Femenino'), ('male', 'Masculino')], default='female', max_length=10)),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FamilyPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_family', models.CharField(max_length=8, unique=True)),
                ('name_family', models.CharField(max_length=32)),
                ('address_family', models.CharField(max_length=128)),
                ('relationship', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Intolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_intolerance', models.CharField(max_length=16)),
                ('code_into', models.CharField(max_length=8, unique=True)),
                ('description_intolerance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_room', models.CharField(max_length=8, unique=True)),
                ('room_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_tutor', models.CharField(max_length=11, unique=True)),
                ('name_tutor', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=32)),
                ('workplace', models.CharField(max_length=32)),
                ('work_address', models.CharField(max_length=128)),
                ('tutor_address', models.CharField(max_length=128)),
                ('civil_status', models.CharField(max_length=8)),
                ('other_income', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Expedient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_expedient', models.CharField(max_length=8, unique=True)),
                ('date_letter', models.DateField(max_length=32)),
                ('date_ticket', models.DateField(max_length=32)),
                ('child_expedient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.child')),
            ],
        ),
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son', models.IntegerField()),
                ('members', models.IntegerField()),
                ('tutor_economy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_disease', models.CharField(max_length=8, unique=True)),
                ('name_disease', models.CharField(max_length=16)),
                ('description_disease', models.TextField()),
                ('child_disease', models.ManyToManyField(null=True, related_name='child_disease', to='main.child')),
            ],
        ),
    ]
