# Generated by Django 4.1.7 on 2023-02-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_child_age_alter_child_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='room_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
        migrations.AddField(
            model_name='child',
            name='room_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
    ]
