# Generated by Django 4.1.7 on 2023-02-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_room_article_child_room_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='room_article',
        ),
        migrations.AddField(
            model_name='article',
            name='name_article',
            field=models.CharField(default='', max_length=32, verbose_name='Nombre del artículo'),
        ),
        migrations.AddField(
            model_name='room',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.article', verbose_name='Artículos'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_article',
            field=models.TextField(verbose_name='Descripción del artículo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='child',
            name='address_child',
            field=models.CharField(max_length=128, verbose_name='Dirección de residencia'),
        ),
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='child',
            name='care_area',
            field=models.CharField(max_length=32, verbose_name='Área de atención'),
        ),
        migrations.AlterField(
            model_name='child',
            name='ci_child',
            field=models.CharField(max_length=11, unique=True, verbose_name='Carne de identidad'),
        ),
        migrations.AlterField(
            model_name='child',
            name='cp',
            field=models.CharField(max_length=32, verbose_name='Consejo popular'),
        ),
        migrations.AlterField(
            model_name='child',
            name='eyes_color',
            field=models.CharField(max_length=32, verbose_name='Color de ojos'),
        ),
        migrations.AlterField(
            model_name='child',
            name='hair_color',
            field=models.CharField(max_length=32, verbose_name='Color del pelo'),
        ),
        migrations.AlterField(
            model_name='child',
            name='height',
            field=models.FloatField(verbose_name='Altura(m)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='name_child',
            field=models.CharField(max_length=32, verbose_name='Nombre y apellidos'),
        ),
        migrations.AlterField(
            model_name='child',
            name='room_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Salon'),
        ),
        migrations.AlterField(
            model_name='child',
            name='sexo',
            field=models.CharField(choices=[('female', 'Femenino'), ('male', 'Masculino')], default='female', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='child',
            name='skin_color',
            field=models.CharField(max_length=32, verbose_name='Color de piel'),
        ),
        migrations.AlterField(
            model_name='child',
            name='weight',
            field=models.IntegerField(verbose_name='Peso(kg)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description_disease',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name_disease',
            field=models.CharField(max_length=16, verbose_name='Nombre de la enfermedad'),
        ),
        migrations.AlterField(
            model_name='economy',
            name='members',
            field=models.IntegerField(verbose_name='Número de miembros del nucleo familiar'),
        ),
        migrations.AlterField(
            model_name='economy',
            name='son',
            field=models.IntegerField(verbose_name='Número de hijos en el circulo'),
        ),
        migrations.AlterField(
            model_name='expedient',
            name='date_letter',
            field=models.DateField(max_length=32, verbose_name='Fecha de asignación de la carta'),
        ),
        migrations.AlterField(
            model_name='expedient',
            name='date_ticket',
            field=models.DateField(max_length=32, verbose_name='Fecha de asignación de la boleta'),
        ),
        migrations.AlterField(
            model_name='familypickup',
            name='address_family',
            field=models.CharField(max_length=128, verbose_name='Direción del familiar'),
        ),
        migrations.AlterField(
            model_name='familypickup',
            name='name_family',
            field=models.CharField(max_length=32, verbose_name='Nombre del familiar'),
        ),
        migrations.AlterField(
            model_name='familypickup',
            name='relationship',
            field=models.CharField(max_length=32, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='intolerance',
            name='description_intolerance',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='intolerance',
            name='name_intolerance',
            field=models.CharField(max_length=16, verbose_name='Nombre de la intolerancia'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(verbose_name='Número del salon'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='ci_tutor',
            field=models.CharField(max_length=11, unique=True, verbose_name='Carned de identidad'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='civil_status',
            field=models.CharField(max_length=8, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name_tutor',
            field=models.CharField(max_length=32, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='other_income',
            field=models.IntegerField(verbose_name='Otros ingresos'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='position',
            field=models.CharField(max_length=32, verbose_name='Cargo donde trabajo'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='salary',
            field=models.FloatField(verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_address',
            field=models.CharField(max_length=128, verbose_name='Dirección de residencia'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='work_address',
            field=models.CharField(max_length=128, verbose_name='Dirección de trabajo'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='workplace',
            field=models.CharField(max_length=32, verbose_name='Centro de trabajo'),
        ),
    ]
