# Generated by Django 4.1.7 on 2023-02-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_article_options_alter_child_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedient',
            name='child',
        ),
        migrations.AddField(
            model_name='child',
            name='expedient',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.expedient', verbose_name='Expediente'),
        ),
    ]
