# Generated by Django 4.1.7 on 2023-02-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_child_diseases_alter_child_intolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='diseases',
            field=models.ManyToManyField(blank=True, to='main.disease', verbose_name='Enfermedades'),
        ),
        migrations.AlterField(
            model_name='child',
            name='intolerance',
            field=models.ManyToManyField(blank=True, to='main.intolerance', verbose_name='Intolerancias'),
        ),
    ]
