# Generated by Django 4.1.7 on 2023-02-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_child_diseases_alter_child_intolerance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Matricular niño', 'verbose_name_plural': 'Matricular niños'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room', verbose_name='Salon'),
        ),
    ]
