# Generated by Django 4.1.7 on 2023-02-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_child_options_remove_room_article_article_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room', verbose_name='Salon'),
        ),
    ]
