# Generated by Django 4.1.7 on 2023-02-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_article_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Niño', 'verbose_name_plural': 'Niños'},
        ),
    ]
