# Generated by Django 4.1.7 on 2023-03-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_economy_son'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description_article',
            field=models.TextField(blank=True, verbose_name='Descripción del artículo'),
        ),
        migrations.AlterField(
            model_name='child',
            name='expedient',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.expedient', verbose_name='Expediente'),
        ),
    ]
