# Generated by Django 4.1.7 on 2023-03-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_article_description_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='expedient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.expedient', verbose_name='Expediente'),
        ),
    ]
