# Generated by Django 4.1.7 on 2023-03-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_child_expedient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='child',
        ),
        migrations.AddField(
            model_name='child',
            name='tutor',
            field=models.ManyToManyField(to='main.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room', verbose_name='Salón'),
        ),
        migrations.AlterField(
            model_name='child',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Salón'),
        ),
    ]
