# Generated by Django 4.1.7 on 2023-03-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_article_options_remove_tutor_child_child_tutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economy',
            name='members',
            field=models.IntegerField(verbose_name='Número de miembros del ncleo familiar'),
        ),
    ]
