# Generated by Django 4.1.7 on 2023-03-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_economy_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateTimeField()),
                ('type', models.CharField(choices=[('tardanza', 'tardanza'), ('presente', 'presente'), ('ausencia', 'ausencia')], max_length=255)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.child')),
            ],
        ),
    ]
