# Generated by Django 4.1.7 on 2023-03-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateTimeField(verbose_name='Día de asistencia '),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.child', verbose_name='Niño'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('tardanza', 'tardanza'), ('ausencia', 'ausencia'), ('presente', 'presente')], default='presente', max_length=255, verbose_name='Típo'),
        ),
    ]
