# Generated by Django 4.1.7 on 2023-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('ausencia', 'ausencia'), ('presente', 'presente'), ('tardanza', 'tardanza')], default='presente', max_length=255, verbose_name='Típo'),
        ),
    ]
