# Generated by Django 4.1.7 on 2023-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_attendance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('vacaciones', 'vacaciones'), ('certificado', 'certificado'), ('ausencia', 'ausencia')], default='presente', max_length=255, verbose_name='Típo'),
        ),
    ]
