from main.admin.article import Article
from main.admin.child import Child
from main.admin.disease import Disease
from main.admin.economy import Economy
from main.admin.expedient import Expedient
from main.admin.family_pickup import FamilyPickup
from main.admin.intolerance import Intolerance
from main.admin.room import Room
from main.admin.tutor import Tutor
